version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  replay-engine:
    build: .
    ports:
      - "8000:8000"
      - "8050:8050"
    environment:
      - REDIS_URL=redis://redis:6379
      - STREAM_KEY=logs:stream
      - REPLAY_SHARED_TOKEN=mysecret
    depends_on:
      - redis
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  redis-data:
  grafana-data: