redis:
  # Connect to shared Redis from logging hook
  host: universal-logging-redis
  port: 6379
  password: mysecret
  url: redis://:mysecret@universal-logging-redis:6379
  stream_key: logs:stream
  consumer_group: replay_group
  consumer_name: consumer-1

stream:
  key: logs:stream
  group: replay_group
  consumer: consumer-1

replay:
  max_events_per_batch: 100
  checkpoint_every: 50
  default_speed: 1.0

bug_detection:
  error_levels: ["ERROR", "FATAL", "CRITICAL"]
  gap_threshold_seconds: 300
  correlation_timeout_hours: 1
  repeated_error_threshold: 3