version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=mysecret
    command: redis-server --requirepass mysecret

  replay-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8050:8050"
    environment:
      - REDIS_URL=redis://:mysecret@redis:6379
      - STREAM_KEY=logs:stream
      - REPLAY_SHARED_TOKEN=mysecret
    depends_on:
      - redis
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - replay-engine

volumes:
  redis-data:
  grafana-data: